import * as RNFS from '@dr.pogodin/react-native-fs';
import {base64ToFloat32Array, computeMelFromPcm, decodeAndMel, float32ArrayToBase64} from './audio';
import {analyzeEmbeddingAndMoods, loadModels, runEmbedding} from './tflite';
import {resolveStreamUrl} from '../stream/resolver';
import {openVibesDb} from '../db/vibesDb';
import {cosineSimilarity} from './cosine';

export {cosineSimilarity};

// Plan D Task 5 -- THE ON-DEVICE PROOF: for each golden fixture (essentia
// mel + embedding, dumped by analyzer/scripts/gen_fixtures.py --dump), run
// its PCM through the Kotlin mel port (bypassing decodeToPcm -- the
// fixtures are already 16kHz mono, matching essentia's MonoLoader input,
// so this isolates the mel-vs-embedding pipeline from decoder/resampler
// concerns) -> TFLite embedding, and compare via cosine similarity to
// essentia's own embedding for the same clip. Requires the device_fixtures/
// files (PCM .f32 + manifest.json, generated by a one-off script during
// Task 5 and pushed via `adb push` + `adb shell run-as` into the app's
// private storage -- see the Task 5 report for the exact commands) to
// already be present under `${RNFS.DocumentDirectoryPath}/flowstate_fixtures/`.

export const FIXTURES_DIR_NAME = 'flowstate_fixtures';

export function fixturesDir(): string {
  return `${RNFS.DocumentDirectoryPath}/${FIXTURES_DIR_NAME}`;
}

export interface FixtureManifestEntry {
  clip: string;
  pcmFile: string;
  nSamples: number;
  embeddingB64: string;
  moods: Record<string, number>;
}

export interface FixtureManifest {
  fixtures: FixtureManifestEntry[];
}

export interface FixtureParityResult {
  clip: string;
  cosine: number;
  numPatches: number;
}

export async function loadManifest(): Promise<FixtureManifest> {
  const path = `${fixturesDir()}/manifest.json`;
  if (!(await RNFS.exists(path))) {
    throw new Error(
      `fixture manifest not found at ${path} -- push device_fixtures/ to the device first (see Task 5 report for the adb commands)`,
    );
  }
  const text = await RNFS.readFile(path, 'utf8');
  return JSON.parse(text) as FixtureManifest;
}

/**
 * Runs the full on-device parity check across every pushed fixture. THE
 * GATE: every fixture's cosine must be >= 0.99 (mirrors
 * analyzer/tests/test_mel_parity.py's EMBEDDING_COSINE_GATE).
 */
export async function runMelFixtureParity(
  onProgress?: (clip: string, index: number, total: number) => void,
): Promise<{results: FixtureParityResult[]; minCosine: number}> {
  await loadModels();
  const manifest = await loadManifest();
  if (manifest.fixtures.length === 0) {
    throw new Error('fixture manifest has zero entries');
  }

  const results: FixtureParityResult[] = [];
  for (let i = 0; i < manifest.fixtures.length; i++) {
    const fx = manifest.fixtures[i];
    onProgress?.(fx.clip, i, manifest.fixtures.length);

    const pcmPath = `${fixturesDir()}/${fx.pcmFile}`;
    const pcmB64 = await RNFS.readFile(pcmPath, 'base64');
    const pcm = base64ToFloat32Array(pcmB64);
    if (pcm.length !== fx.nSamples) {
      throw new Error(`${fx.clip}: pushed PCM has ${pcm.length} samples, manifest says ${fx.nSamples}`);
    }

    const patches = await computeMelFromPcm(pcm);
    if (patches.length === 0) {
      throw new Error(`${fx.clip}: produced 0 mel patches (clip too short for a 187-frame patch)`);
    }

    const embedding = await runEmbedding(patches);
    const reference = base64ToFloat32Array(fx.embeddingB64);
    const cosine = cosineSimilarity(embedding, reference);
    results.push({clip: fx.clip, cosine, numPatches: patches.length});
  }

  const minCosine = Math.min(...results.map(r => r.cosine));
  return {results, minCosine};
}

export interface RealSongSanityResult {
  videoId: string;
  numPatches: number;
  embeddingLength: number;
  embeddingNorm: number;
  moods: Record<string, number>;
}

// Fallback videoId used only when the device has no synced library yet
// (fresh install/dev harness run) -- a long-lived, globally-available public
// video, purely so this decode-path sanity check has SOME real audio to
// exercise without requiring login/sync first. resolveStreamUrl() itself is
// always anonymous (see stream/resolver.ts), so no login is needed either way.
const FALLBACK_VIDEO_ID = 'dQw4w9WgXcQ';

/**
 * Sanity-checks the PRODUCTION decode path (decodeToPcm's MediaCodec
 * decode + resample + middle-120s-slice, then computeMel) end-to-end on a
 * real downloaded song. No essentia reference exists for this clip -- this
 * only checks the pipeline runs and produces non-degenerate output (no
 * NaNs, a plausible embedding norm, >=1 patch), NOT parity.
 */
export async function runRealSongDecodeSanity(): Promise<RealSongSanityResult> {
  const db = await openVibesDb();
  const songs = db?.getAllSongs() ?? [];
  const videoId = songs.length > 0 ? songs[0].videoId : FALLBACK_VIDEO_ID;

  const {url, headers} = await resolveStreamUrl(videoId);
  const destPath = `${RNFS.CachesDirectoryPath}/mel_probe_${videoId}.m4a`;
  const {promise} = RNFS.downloadFile({fromUrl: url, toFile: destPath, headers});
  const download = await promise;
  if (download.statusCode !== 200 && download.statusCode !== 206) {
    throw new Error(`download failed: status ${download.statusCode}`);
  }

  try {
    const patches = await decodeAndMel(destPath);
    if (patches.length === 0) {
      throw new Error(`${videoId}: decoded audio produced 0 mel patches`);
    }
    const {embedding, moods} = await analyzeEmbeddingAndMoods(patches);
    let sumSq = 0;
    for (let i = 0; i < embedding.length; i++) {
      if (!Number.isFinite(embedding[i])) {
        throw new Error(`${videoId}: embedding contains a non-finite value at index ${i}`);
      }
      sumSq += embedding[i] * embedding[i];
    }
    return {
      videoId,
      numPatches: patches.length,
      embeddingLength: embedding.length,
      embeddingNorm: Math.sqrt(sumSq),
      moods,
    };
  } finally {
    await RNFS.unlink(destPath).catch(() => {});
  }
}

// Real-song END-TO-END parity (closes the gap the fixture-based
// runMelFixtureParity above deliberately leaves open): that harness injects
// already-16kHz-mono PCM directly, bypassing decodeToPcm's MediaCodec
// decode + LINEAR resample front-end (AudioDecoder.kt) entirely, so it can
// prove [mel -> model] parity but never [decode -> resample] parity. This
// runs the FULL production path (decodeAndMel == decodeToPcm's decoder +
// resampler + middle-120s-slice, then computeMel -> TFLite embedding) on
// real downloaded audio files pushed to the device beforehand (adb push to
// `realSongProbeDir()`, i.e. the app's own external files dir -- no root/
// run-as needed even for a non-debuggable release build), so it can be
// compared against essentia's OWN decode+resample (MonoLoader) on the
// IDENTICAL file (analyzer/scripts/real_song_reference.py, run in the
// flowstate-analyzer Docker image) via cosine similarity. See
// .superpowers/sdd/real-song-parity-report.md for the measured numbers.

const REAL_SONG_PROBE_DIR_NAME = 'flowstate_probe';

/** App's own external-files-dir subfolder pushed audio files + results live in. */
export function realSongProbeDir(): string {
  return `${RNFS.ExternalDirectoryPath}/${REAL_SONG_PROBE_DIR_NAME}`;
}

export interface RealSongPathParityEntry {
  videoId: string;
  /** File name (already pushed) under realSongProbeDir(). */
  fileName: string;
}

export interface RealSongPathParityResult {
  videoId: string;
  numPatches: number;
  /** Base64 little-endian float32[200] -- the on-device pooled embedding. */
  embeddingB64: string;
}

/**
 * Runs the real production decode+mel+embedding path on each pushed local
 * file and writes cumulative results (as JSON) to
 * `${realSongProbeDir()}/results.json` after each song, so partial progress
 * survives even if a later file throws. Returns the same array.
 */
export async function runRealSongPathParityProbe(
  entries: RealSongPathParityEntry[],
  onProgress?: (videoId: string, i: number, total: number) => void,
): Promise<RealSongPathParityResult[]> {
  await loadModels();
  const results: RealSongPathParityResult[] = [];
  const resultsPath = `${realSongProbeDir()}/results.json`;
  for (let i = 0; i < entries.length; i++) {
    const {videoId, fileName} = entries[i];
    onProgress?.(videoId, i, entries.length);

    const path = `${realSongProbeDir()}/${fileName}`;
    const patches = await decodeAndMel(path);
    if (patches.length === 0) {
      throw new Error(`${videoId}: decoded audio produced 0 mel patches`);
    }
    const {embedding} = await analyzeEmbeddingAndMoods(patches);
    results.push({
      videoId,
      numPatches: patches.length,
      embeddingB64: float32ArrayToBase64(embedding),
    });
    await RNFS.writeFile(resultsPath, JSON.stringify(results), 'utf8');
  }
  return results;
}
